// rust-svelte-stack/frontend/src/lib/components/ImportWizard.svelte
<script lang="ts">
  // 3-step bulk import wizard — file upload OR link (Google Sheets /
  // OneDrive-Outlook / any public CSV, fetched via backend), column mapping,
  // review & commit. Mirrors React src/shared/ImportWizard.tsx.
  import { api, downloadBlob } from '$lib/api';
  import Modal from './Modal.svelte';
  import NeuLoader from './NeuLoader.svelte';

  export interface Field { key: string; label: string; required?: boolean }
  let {
    open = $bindable(false),
    title = 'Bulk Import',
    fields = [] as Field[],
    templateRows = [] as string[][],
    onImport = async (_rows: Record<string, string>[]): Promise<string> => '',
  } = $props();

  let step = $state(1);
  let headers: string[] = $state([]);
  let rows: string[][] = $state([]);
  let mapping: Record<string, number> = $state({});
  let link = $state('');
  let busy = $state(false);
  let err = $state('');
  let done = $state('');
  let sourceName = $state('');

  $effect(() => { if (!open) { step = 1; headers = []; rows = []; mapping = {}; link = ''; err = ''; done = ''; } });

  function parseCsv(text: string): string[][] {
    const out: string[][] = [];
    let row: string[] = [], cell = '', inQ = false;
    for (let i = 0; i < text.length; i++) {
      const ch = text[i];
      if (inQ) {
        if (ch === '"') { if (text[i + 1] === '"') { cell += '"'; i++; } else inQ = false; }
        else cell += ch;
      } else if (ch === '"') inQ = true;
      else if (ch === ',') { row.push(cell); cell = ''; }
      else if (ch === '\n' || ch === '\r') {
        if (ch === '\r' && text[i + 1] === '\n') i++;
        row.push(cell); cell = '';
        if (row.some((c) => c.trim())) out.push(row);
        row = [];
      } else cell += ch;
    }
    row.push(cell);
    if (row.some((c) => c.trim())) out.push(row);
    return out;
  }

  function ingest(text: string, name: string) {
    const parsed = parseCsv(text);
    if (parsed.length < 2) { err = 'The sheet needs a header row plus at least one data row.'; return; }
    headers = parsed[0].map((h) => h.trim());
    rows = parsed.slice(1);
    sourceName = name;
    const m: Record<string, number> = {};
    fields.forEach((f) => {
      const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');
      const idx = headers.findIndex((h) => norm(h).includes(norm(f.key)) || norm(f.label).includes(norm(h)) || norm(h).includes(norm(f.label)));
      if (idx >= 0) m[f.key] = idx;
    });
    mapping = m;
    err = '';
    step = 2;
  }

  function onFile(e: Event) {
    const f = (e.target as HTMLInputElement).files?.[0];
    if (!f) return;
    if (f.size > 2_000_000) { err = 'File too large — max 2 MB.'; return; }
    const r = new FileReader();
    r.onload = () => ingest(String(r.result || ''), f.name);
    r.readAsText(f);
    (e.target as HTMLInputElement).value = '';
  }

  async function onLink() {
    if (!/^https?:\/\//.test(link.trim())) { err = 'Paste a valid http(s) link — Google Sheets, OneDrive/Outlook or a direct CSV URL.'; return; }
    busy = true; err = '';
    try {
      const { csv } = await api<{ csv: string }>('org/structure/fetch-link', {
        method: 'POST', body: JSON.stringify({ url: link.trim() }),
      });
      ingest(csv, new URL(link.trim()).hostname);
    } catch (e) {
      err = e instanceof Error ? e.message : 'Could not fetch the link';
    } finally { busy = false; }
  }

  function downloadTemplate() {
    const head = fields.map((f) => `"${f.label}"`).join(',');
    const body = templateRows.map((r) => r.map((c) => `"${c}"`).join(',')).join('\n');
    downloadBlob(`${title.toLowerCase().replace(/\s+/g, '-')}-template.csv`, new Blob([head + (body ? '\n' + body : '')], { type: 'text/csv' }));
  }

  const mappedRows = $derived(rows.map((r) => {
    const rec: Record<string, string> = {};
    fields.forEach((f) => {
      const idx = mapping[f.key];
      rec[f.key] = idx !== undefined && idx >= 0 ? (r[idx] || '').trim() : '';
    });
    return rec;
  }).filter((rec) => fields.some((f) => rec[f.key])));
  const requiredMissing = $derived(fields.filter((f) => f.required && mapping[f.key] === undefined));

  async function commit() {
    busy = true; err = '';
    try { done = await onImport(mappedRows); }
    catch (e) { err = e instanceof Error ? e.message : 'Import failed'; }
    finally { busy = false; }
  }
</script>

<Modal bind:open {title} wide>
  <div class="stepper">
    {#each ['Upload', 'Map Columns', 'Review & Import'] as s, i (s)}
      <div class="step">
        <span class="num" class:on={step === i + 1} class:doneN={step > i + 1 || !!done}>{step > i + 1 || done ? '✓' : i + 1}</span>
        <b class:onT={step === i + 1}>{s}</b>
        {#if i < 2}<span class="rail"></span>{/if}
      </div>
    {/each}
  </div>

  {#if done}
    <div class="final">
      <p class="big">✓</p>
      <p class="t">Import complete</p>
      <p class="s">{done}</p>
      <button class="tk-btn-primary act" onclick={() => (open = false)}>Done</button>
    </div>
  {:else if busy && step === 3}
    <NeuLoader label="Importing…" />
  {:else if step === 1}
    <div class="col">
      <div class="tk-inset tmpl">
        <div>
          <b>Download the template</b>
          <small>Fill it in Excel / Google Sheets, then upload or share a link.</small>
        </div>
        <button class="tk-btn-ghost act sm" onclick={downloadTemplate}>Template</button>
      </div>
      <label class="tk-card drop">
        <b>Upload a file</b>
        <small>CSV or Excel-exported CSV · max 2 MB</small>
        <input type="file" accept=".csv,text/csv,.txt" onchange={onFile} />
      </label>
      <div class="or"><span></span><em>or import from a link</em><span></span></div>
      <div class="linkrow">
        <input class="tk-input" bind:value={link} placeholder="Google Sheets, OneDrive / Outlook or direct CSV link…" />
        <button class="tk-btn-primary act sm" disabled={busy} onclick={onLink}>{busy ? 'Fetching…' : 'Fetch'}</button>
      </div>
      <small class="hint">Google Sheets: share as “Anyone with the link”. OneDrive/Outlook: use a download link. Fetched server-side.</small>
      {#if err}<p class="err">{err}</p>{/if}
    </div>
  {:else if step === 2}
    <div class="col">
      <p class="meta"><b>{sourceName}</b> · {rows.length} rows · match each system field to a sheet column.</p>
      {#each fields as f (f.key)}
        <div class="maprow">
          <span class="fname">{f.label}{#if f.required}<i>*</i>{/if}</span>
          <select class="tk-input" value={mapping[f.key] ?? -1}
            onchange={(e) => (mapping = { ...mapping, [f.key]: +(e.target as HTMLSelectElement).value })}>
            <option value={-1}>— Not mapped —</option>
            {#each headers as h, i (i)}<option value={i}>{h || `Column ${i + 1}`}</option>{/each}
          </select>
        </div>
      {/each}
      {#if requiredMissing.length}
        <p class="warn">Map required fields: {requiredMissing.map((f) => f.label).join(', ')}</p>
      {/if}
      <div class="btns">
        <button class="tk-btn-ghost act" onclick={() => (step = 1)}>← Back</button>
        <button class="tk-btn-primary act" disabled={requiredMissing.length > 0} onclick={() => (step = 3)}>Review →</button>
      </div>
    </div>
  {:else}
    <div class="col">
      <p class="meta">Previewing <b>{Math.min(8, mappedRows.length)}</b> of <b>{mappedRows.length}</b> mapped rows.</p>
      <div class="tk-inset preview">
        <table>
          <thead><tr>{#each fields as f (f.key)}<th>{f.label}</th>{/each}</tr></thead>
          <tbody>
            {#each mappedRows.slice(0, 8) as r, i (i)}
              <tr>{#each fields as f (f.key)}<td>{r[f.key] || '—'}</td>{/each}</tr>
            {/each}
          </tbody>
        </table>
      </div>
      {#if err}<p class="err">{err}</p>{/if}
      <div class="btns">
        <button class="tk-btn-ghost act" onclick={() => (step = 2)}>← Back</button>
        <button class="tk-btn-primary act" disabled={busy || !mappedRows.length} onclick={commit}>Import {mappedRows.length} rows</button>
      </div>
    </div>
  {/if}
</Modal>

<style>
  .stepper { display: flex; gap: 8px; margin-bottom: 20px; }
  .step { display: flex; flex: 1; align-items: center; gap: 8px; }
  .num { width: 28px; height: 28px; border-radius: 999px; display: inline-flex; align-items: center;
    justify-content: center; font: 700 12px var(--t-font-body); background: var(--t-surface2);
    box-shadow: var(--t-inset); color: var(--t-muted); flex-shrink: 0; }
  .num.on { color: var(--t-accent); }
  .num.doneN { background: var(--t-accent); color: #fff; box-shadow: var(--t-shadow-card); }
  .step b { font: 700 11.5px var(--t-font-body); color: var(--t-muted); }
  .step b.onT { color: var(--t-ink); }
  .rail { flex: 1; height: 1px; background: color-mix(in srgb, var(--t-ink) 10%, transparent); }
  .col { display: flex; flex-direction: column; gap: 14px; }
  .tmpl { display: flex; justify-content: space-between; align-items: center; gap: 12px;
    padding: 12px 16px; border-radius: 12px; }
  .tmpl b { display: block; font: 700 13px var(--t-font-body); color: var(--t-ink); }
  .tmpl small { font: 500 11.5px var(--t-font-body); color: var(--t-muted); }
  .drop { display: block; text-align: center; padding: 26px; cursor: pointer;
    border: 2px dashed color-mix(in srgb, var(--t-ink) 14%, transparent) !important; }
  .drop b { display: block; font: 700 13.5px var(--t-font-body); color: var(--t-ink); }
  .drop small { font: 500 11.5px var(--t-font-body); color: var(--t-muted); }
  .drop input { display: none; }
  .or { display: flex; align-items: center; gap: 12px; }
  .or span { flex: 1; height: 1px; background: color-mix(in srgb, var(--t-ink) 10%, transparent); }
  .or em { font: 700 10px var(--t-font-body); text-transform: uppercase; letter-spacing: 0.1em;
    color: var(--t-muted); font-style: normal; }
  .linkrow { display: flex; gap: 8px; }
  .linkrow input { flex: 1; padding: 10px 14px; font-size: 12.5px; }
  .hint { font: 500 10.5px var(--t-font-body); color: var(--t-muted); }
  .err { margin: 0; padding: 10px 14px; border-radius: 12px; background: rgba(225, 29, 72, 0.1);
    font: 500 12.5px var(--t-font-body); color: #e11d48; }
  .warn { margin: 0; padding: 10px 14px; border-radius: 12px; background: rgba(217, 119, 6, 0.1);
    font: 600 12px var(--t-font-body); color: #d97706; }
  .meta { margin: 0; font: 500 12.5px var(--t-font-body); color: var(--t-muted); }
  .meta b { color: var(--t-ink); }
  .maprow { display: flex; align-items: center; gap: 12px; }
  .fname { width: 160px; flex-shrink: 0; font: 700 12.5px var(--t-font-body); color: var(--t-ink); }
  .fname i { color: #e11d48; font-style: normal; }
  .maprow select { flex: 1; padding: 8px 10px; font-size: 12.5px; }
  .preview { overflow-x: auto; border-radius: 12px; }
  .preview table { width: 100%; min-width: 480px; border-collapse: collapse; }
  .preview th { padding: 8px 12px; text-align: left; font: 700 10px var(--t-font-body);
    text-transform: uppercase; letter-spacing: 0.08em; color: var(--t-muted);
    border-bottom: 1px solid color-mix(in srgb, var(--t-ink) 8%, transparent); }
  .preview td { padding: 8px 12px; font: 500 12px var(--t-font-body); color: color-mix(in srgb, var(--t-ink) 80%, transparent);
    border-bottom: 1px solid color-mix(in srgb, var(--t-ink) 6%, transparent); }
  .btns { display: flex; justify-content: space-between; padding-top: 4px; }
  .act { padding: 10px 18px; font: 600 13px var(--t-font-body); }
  .act.sm { padding: 8px 14px; font-size: 12px; }
  .final { text-align: center; padding: 32px 0; }
  .final .big { font-size: 38px; color: var(--t-accent); margin: 0; }
  .final .t { font: 600 17px var(--t-font-display); color: var(--t-ink); margin: 8px 0 2px; }
  .final .s { font: 500 13px var(--t-font-body); color: var(--t-muted); margin: 0 0 18px; }
</style>

// src/shared/ImportWizard.tsx
import { useState, useMemo } from 'react';
import { Upload, Link2, Download, ArrowRight, ArrowLeft, CheckCircle2, FileSpreadsheet, X } from 'lucide-react';
import { api } from '../lib/api';
import { Modal, btnPrimary, btnGhost, inputCls, labelCls, NeuLoader } from './primitives';
import { downloadBlob } from './Charts';

/* ============================================================
   3-step bulk import wizard used across Org Structure:
     Step 1 · Upload  — download template, upload CSV/Excel-CSV,
               OR paste a link (Google Sheets, OneDrive/Outlook,
               any public CSV URL — fetched server-side, no CORS)
     Step 2 · Map Columns — align sheet headers to system fields
     Step 3 · Review & Import — preview mapped rows, commit
   ============================================================ */

export interface WizardField { key: string; label: string; required?: boolean }

/* Minimal robust CSV parser (quotes, commas, CRLF). */
function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [], cell = '', inQ = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQ) {
      if (ch === '"') {
        if (text[i + 1] === '"') { cell += '"'; i++; }
        else inQ = false;
      } else cell += ch;
    } else if (ch === '"') inQ = true;
    else if (ch === ',') { row.push(cell); cell = ''; }
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i++;
      row.push(cell); cell = '';
      if (row.some((c) => c.trim() !== '')) rows.push(row);
      row = [];
    } else cell += ch;
  }
  row.push(cell);
  if (row.some((c) => c.trim() !== '')) rows.push(row);
  return rows;
}

const guessMatch = (header: string, field: WizardField) => {
  const h = header.toLowerCase().replace(/[^a-z0-9]/g, '');
  const f = (field.label + field.key).toLowerCase().replace(/[^a-z0-9]/g, '');
  return f.includes(h) || h.includes(field.key.toLowerCase().replace(/[^a-z0-9]/g, '')) || h.includes(field.label.toLowerCase().replace(/[^a-z0-9]/g, ''));
};

export default function ImportWizard({ open, onClose, title, fields, templateRows, onImport }: {
  open: boolean;
  onClose: () => void;
  title: string;
  fields: WizardField[];
  /** sample rows for the downloadable template (header auto-generated from fields) */
  templateRows?: string[][];
  onImport: (rows: Record<string, string>[]) => Promise<string>;
}) {
  const [step, setStep] = useState(1);
  const [headers, setHeaders] = useState<string[]>([]);
  const [rows, setRows] = useState<string[][]>([]);
  const [mapping, setMapping] = useState<Record<string, number>>({});
  const [link, setLink] = useState('');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const [done, setDone] = useState('');
  const [sourceName, setSourceName] = useState('');

  const reset = () => { setStep(1); setHeaders([]); setRows([]); setMapping({}); setLink(''); setErr(''); setDone(''); setSourceName(''); };
  const close = () => { reset(); onClose(); };

  const ingest = (text: string, name: string) => {
    const parsed = parseCsv(text);
    if (parsed.length < 2) { setErr('The sheet needs a header row plus at least one data row.'); return; }
    const hdr = parsed[0].map((h) => h.trim());
    setHeaders(hdr);
    setRows(parsed.slice(1));
    setSourceName(name);
    // auto-guess mapping
    const m: Record<string, number> = {};
    fields.forEach((f) => {
      const idx = hdr.findIndex((h) => guessMatch(h, f));
      if (idx >= 0) m[f.key] = idx;
    });
    setMapping(m);
    setErr('');
    setStep(2);
  };

  const onFile = (file: File) => {
    if (file.size > 2_000_000) { setErr('File too large — max 2 MB.'); return; }
    const reader = new FileReader();
    reader.onload = () => ingest(String(reader.result || ''), file.name);
    reader.readAsText(file);
  };

  const onLink = async () => {
    if (!/^https?:\/\//.test(link.trim())) { setErr('Paste a valid http(s) link — Google Sheets, OneDrive/Outlook or a direct CSV URL.'); return; }
    setBusy(true); setErr('');
    try {
      const { csv } = await api<{ csv: string }>('orgstructure', {
        method: 'POST', body: JSON.stringify({ resource: 'fetch_link', url: link.trim() }),
      });
      ingest(csv, new URL(link.trim()).hostname);
    } catch (e) {
      setErr(e instanceof Error ? e.message : 'Could not fetch the link');
    } finally { setBusy(false); }
  };

  const downloadTemplate = () => {
    const head = fields.map((f) => `"${f.label}"`).join(',');
    const body = (templateRows || []).map((r) => r.map((c) => `"${c}"`).join(',')).join('\n');
    downloadBlob(`${title.toLowerCase().replace(/\s+/g, '-')}-template.csv`, new Blob([head + (body ? '\n' + body : '')], { type: 'text/csv' }));
  };

  const mappedRows = useMemo(() =>
    rows.map((r) => {
      const rec: Record<string, string> = {};
      fields.forEach((f) => {
        const idx = mapping[f.key];
        rec[f.key] = idx !== undefined && idx >= 0 ? (r[idx] || '').trim() : '';
      });
      return rec;
    }).filter((rec) => fields.some((f) => rec[f.key])),
  [rows, mapping, fields]);

  const requiredMissing = fields.filter((f) => f.required && mapping[f.key] === undefined);

  const commit = async () => {
    setBusy(true); setErr('');
    try {
      const msg = await onImport(mappedRows);
      setDone(msg);
    } catch (e) {
      setErr(e instanceof Error ? e.message : 'Import failed');
    } finally { setBusy(false); }
  };

  return (
    <Modal open={open} onClose={close} title={title} wide>
      {/* stepper */}
      <div className="mb-5 flex items-center gap-2">
        {['Upload', 'Map Columns', 'Review & Import'].map((s, i) => (
          <div key={s} className="flex flex-1 items-center gap-2">
            <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full font-body text-[12px] font-bold ${step > i + 1 || done ? 'tk-btn-primary !p-0' : step === i + 1 ? 'tk-inset text-primary' : 'tk-chip text-muted'}`}>
              {step > i + 1 || done ? <CheckCircle2 size={14} /> : i + 1}
            </span>
            <span className={`font-body text-[11.5px] font-bold ${step === i + 1 ? 'text-ink' : 'text-muted'}`}>{s}</span>
            {i < 2 && <span className="h-px flex-1 bg-(--t-border) tk-divider border-t" />}
          </div>
        ))}
      </div>

      {done ? (
        <div className="py-8 text-center">
          <CheckCircle2 size={40} className="mx-auto mb-3 text-primary" />
          <p className="font-display text-[17px] font-semibold text-ink">Import complete</p>
          <p className="mt-1 font-body text-[13px] text-muted">{done}</p>
          <button onClick={close} className={btnPrimary + ' mt-5'}>Done</button>
        </div>
      ) : busy && step === 3 ? (
        <NeuLoader label="Importing…" />
      ) : (
        <>
          {/* ============ STEP 1 · UPLOAD ============ */}
          {step === 1 && (
            <div className="space-y-4">
              <div className="tk-inset flex items-center justify-between gap-3 rounded-xl px-4 py-3">
                <div className="flex items-center gap-2.5">
                  <FileSpreadsheet size={16} className="text-primary" />
                  <div>
                    <p className="font-body text-[13px] font-bold text-ink">Download the template</p>
                    <p className="font-body text-[11.5px] text-muted">Fill it in Excel / Google Sheets, then upload or share a link.</p>
                  </div>
                </div>
                <button onClick={downloadTemplate} className={btnGhost + ' !py-2 text-[12px]'}><Download size={13} /> Template</button>
              </div>

              <label className="tk-card block cursor-pointer border-2 border-dashed !border-(--t-border) p-6 text-center transition hover:-translate-y-0.5">
                <Upload size={22} className="mx-auto mb-2 text-primary" />
                <p className="font-body text-[13.5px] font-bold text-ink">Upload a file</p>
                <p className="font-body text-[11.5px] text-muted">CSV or Excel-exported CSV · max 2 MB</p>
                <input type="file" accept=".csv,text/csv,.txt" className="hidden"
                  onChange={(e) => { const f = e.target.files?.[0]; if (f) onFile(f); e.target.value = ''; }} />
              </label>

              <div className="flex items-center gap-3">
                <span className="h-px flex-1 border-t tk-divider" />
                <span className="font-body text-[10px] font-bold uppercase tracking-wider text-muted">or import from a link</span>
                <span className="h-px flex-1 border-t tk-divider" />
              </div>

              <div>
                <label className={labelCls}>Paste a share link</label>
                <div className="flex gap-2">
                  <div className="tk-input flex flex-1 items-center gap-2 px-3">
                    <Link2 size={13} className="shrink-0 text-muted" />
                    <input value={link} onChange={(e) => setLink(e.target.value)}
                      placeholder="Google Sheets, OneDrive / Outlook or direct CSV link…"
                      className="w-full bg-transparent py-2.5 font-body text-[12.5px] text-ink outline-none placeholder:text-muted" />
                  </div>
                  <button onClick={onLink} disabled={busy} className={btnPrimary + ' shrink-0 !py-2 text-[12.5px]'}>
                    {busy ? 'Fetching…' : 'Fetch'}
                  </button>
                </div>
                <p className="mt-1.5 font-body text-[10.5px] text-muted">
                  Google Sheets: share as “Anyone with the link”. OneDrive/Outlook: use a download link. Fetched securely server-side.
                </p>
              </div>
              {err && <p className="rounded-xl bg-rose-500/10 px-3.5 py-2.5 font-body text-[12.5px] text-rose-500">{err}</p>}
            </div>
          )}

          {/* ============ STEP 2 · MAP COLUMNS ============ */}
          {step === 2 && (
            <div className="space-y-4">
              <p className="font-body text-[12.5px] text-muted">
                <b className="text-ink">{sourceName}</b> · {rows.length} rows · match each system field to a column from your sheet.
              </p>
              <div className="space-y-2.5">
                {fields.map((f) => (
                  <div key={f.key} className="flex items-center gap-3">
                    <span className="w-40 shrink-0 font-body text-[12.5px] font-bold text-ink">
                      {f.label} {f.required && <span className="text-rose-500">*</span>}
                    </span>
                    <ArrowLeft size={13} className="shrink-0 text-muted" />
                    <select value={mapping[f.key] ?? -1}
                      onChange={(e) => setMapping((m) => ({ ...m, [f.key]: +e.target.value }))}
                      className={inputCls + ' !py-2 text-[12.5px]'}>
                      <option value={-1}>— Not mapped —</option>
                      {headers.map((h, i) => <option key={i} value={i}>{h || `Column ${i + 1}`}</option>)}
                    </select>
                  </div>
                ))}
              </div>
              {requiredMissing.length > 0 && (
                <p className="rounded-xl bg-amber-500/10 px-3.5 py-2.5 font-body text-[12px] font-semibold text-amber-600">
                  Map required fields: {requiredMissing.map((f) => f.label).join(', ')}
                </p>
              )}
              <div className="flex justify-between pt-1">
                <button onClick={() => setStep(1)} className={btnGhost}><ArrowLeft size={14} /> Back</button>
                <button onClick={() => setStep(3)} disabled={requiredMissing.length > 0} className={btnPrimary}>
                  Review <ArrowRight size={14} />
                </button>
              </div>
            </div>
          )}

          {/* ============ STEP 3 · REVIEW & IMPORT ============ */}
          {step === 3 && (
            <div className="space-y-4">
              <p className="font-body text-[12.5px] text-muted">
                Previewing <b className="text-ink">{Math.min(8, mappedRows.length)}</b> of <b className="text-ink">{mappedRows.length}</b> mapped rows.
              </p>
              <div className="tk-inset overflow-x-auto rounded-xl">
                <table className="w-full min-w-[480px]">
                  <thead>
                    <tr className="border-b tk-divider">
                      {fields.map((f) => (
                        <th key={f.key} className="px-3 py-2 text-left font-body text-[10px] font-bold uppercase tracking-wider text-muted">{f.label}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {mappedRows.slice(0, 8).map((r, i) => (
                      <tr key={i} className="border-b tk-divider">
                        {fields.map((f) => (
                          <td key={f.key} className="px-3 py-2 font-body text-[12px] text-ink/80">
                            {r[f.key] || <span className="text-muted">—</span>}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {err && <p className="rounded-xl bg-rose-500/10 px-3.5 py-2.5 font-body text-[12.5px] text-rose-500">{err}</p>}
              <div className="flex justify-between pt-1">
                <button onClick={() => setStep(2)} className={btnGhost}><ArrowLeft size={14} /> Back</button>
                <div className="flex gap-2">
                  <button onClick={close} className={btnGhost}><X size={14} /> Cancel</button>
                  <button onClick={commit} disabled={busy || mappedRows.length === 0} className={btnPrimary}>
                    <Upload size={14} /> Import {mappedRows.length} rows
                  </button>
                </div>
              </div>
            </div>
          )}
        </>
      )}
    </Modal>
  );
}
