// rust-svelte-stack/frontend/src/lib/components/Select.svelte
<script lang="ts">
  // Mirror of React src/shared/Select.tsx — single & multi with search,
  // chips, clear, flip-aware panel.
  export interface Option { value: string; label: string }
  let {
    options = [] as Option[],
    multi = false,
    value = $bindable(null as string | null),
    values = $bindable([] as string[]),
    placeholder = 'Select…',
  } = $props();

  let open = $state(false);
  let q = $state('');
  let openUp = $state(false);
  let root: HTMLDivElement;

  const filtered = $derived(options.filter((o) => o.label.toLowerCase().includes(q.toLowerCase())));
  const selected = $derived(multi ? values : value ? [value] : []);

  function toggleOpen() {
    const r = root.getBoundingClientRect();
    openUp = window.innerHeight - r.bottom < 300 && r.top > 300;
    open = !open;
    q = '';
  }
  function pick(v: string) {
    if (multi) values = values.includes(v) ? values.filter((x) => x !== v) : [...values, v];
    else { value = value === v ? null : v; open = false; }
  }
</script>

<svelte:window onmousedown={(e) => { if (open && root && !root.contains(e.target as Node)) open = false; }} />

<div class="root" bind:this={root}>
  <button class="tk-input field" onclick={toggleOpen}>
    {#if selected.length === 0}<span class="ph">{placeholder}</span>
    {:else if multi}
      {#each selected as v}
        <span class="tk-chip chip">{options.find((o) => o.value === v)?.label ?? v}
          <button onclick={(e) => { e.stopPropagation(); pick(v); }}>×</button></span>
      {/each}
    {:else}{options.find((o) => o.value === selected[0])?.label}{/if}
    <span class="caret" class:up={open}>▾</span>
  </button>

  {#if open}
    <div class="tk-pop panel" class:openUp>
      <input class="tk-input" placeholder="Search…" bind:value={q} />
      <div class="list">
        {#each filtered as o}
          <button class="opt" class:on={selected.includes(o.value)} onclick={() => pick(o.value)}>
            {o.label}{selected.includes(o.value) ? ' ✓' : ''}
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>

<style>
  .root { position: relative; }
  .field { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; width: 100%;
    padding: 9px 14px; font: 500 14px var(--t-font-body); color: var(--t-ink); text-align: left; }
  .ph { color: var(--t-muted); }
  .chip { padding: 2px 8px; font: 700 11.5px var(--t-font-body); }
  .caret { margin-left: auto; color: var(--t-muted); transition: transform 0.15s; }
  .caret.up { transform: rotate(180deg); }
  .panel { position: absolute; left: 0; top: calc(100% + 6px); width: 260px; padding: 10px; z-index: 60; }
  .panel.openUp { top: auto; bottom: calc(100% + 6px); }
  .panel input { width: 100%; padding: 7px 10px; margin-bottom: 8px; font-size: 13px; }
  .list { max-height: 220px; overflow-y: auto; }
  .opt { display: block; width: 100%; text-align: left; padding: 8px 10px; border-radius: 8px;
    font: 500 13px var(--t-font-body); color: var(--t-ink); }
  .opt:hover { background: color-mix(in srgb, var(--t-accent) 8%, transparent); }
  .opt.on { color: var(--t-accent); font-weight: 700; }
</style>

// src/shared/Select.tsx
import { useState, useMemo } from 'react';
import { ChevronDown, Check, X, Search } from 'lucide-react';
import { useFlip, Popover } from './primitives';

export interface Option { value: string; label: string; hint?: string }

interface BaseProps {
  options: Option[];
  placeholder?: string;
  searchable?: boolean;
  className?: string;
  disabled?: boolean;
  /** Max chips shown in the multi trigger before collapsing to "+N" (keeps the field one line tall). */
  maxChips?: number;
}
interface SingleProps extends BaseProps { multi?: false; value: string | null; onChange: (v: string | null) => void }
interface MultiProps extends BaseProps { multi: true; values: string[]; onChange: (v: string[]) => void }

export default function Select(props: SingleProps | MultiProps) {
  const { options, placeholder = 'Select…', searchable = true, className = '', disabled, maxChips = 2 } = props;
  const [open, setOpen] = useState(false);
  const [q, setQ] = useState('');
  const { anchorRef, dir, measure } = useFlip(300);

  const selected: string[] = props.multi ? props.values : props.value ? [props.value] : [];
  const filtered = useMemo(() => {
    const t = q.trim().toLowerCase();
    return t ? options.filter((o) => o.label.toLowerCase().includes(t)) : options;
  }, [q, options]);

  const toggle = (v: string) => {
    if (props.multi) {
      props.onChange(selected.includes(v) ? selected.filter((x) => x !== v) : [...selected, v]);
    } else {
      props.onChange(v === props.value ? null : v);
      setOpen(false);
    }
  };

  const clear = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (props.multi) props.onChange([]); else props.onChange(null);
  };

  const labelFor = (v: string) => options.find((o) => o.value === v)?.label || v;

  return (
    <div ref={anchorRef} className={`relative ${className}`}>
      <button type="button" disabled={disabled}
        onClick={() => { measure(); setOpen((o) => !o); setQ(''); }}
        className="tk-input flex w-full items-center justify-between gap-2 px-3.5 py-2.5 text-left font-body text-sm disabled:opacity-50">
        <span className="flex min-w-0 flex-1 items-center gap-1.5 overflow-hidden">
          {selected.length === 0 && <span className="truncate text-muted">{placeholder}</span>}
          {props.multi
            ? <>
                {selected.slice(0, maxChips).map((v) => (
                  <span key={v} className="tk-chip flex shrink-0 items-center gap-1 px-2 py-0.5 text-[11.5px] font-bold text-ink/80">
                    <span className="max-w-[80px] truncate">{labelFor(v)}</span>
                    <span role="button" onClick={(e) => { e.stopPropagation(); toggle(v); }} className="cursor-pointer text-muted hover:text-rose-500"><X size={11} /></span>
                  </span>
                ))}
                {selected.length > maxChips && (
                  <span className="tk-chip shrink-0 px-2 py-0.5 text-[11.5px] font-bold text-primary" data-tip={selected.slice(maxChips).map(labelFor).join(', ')}>
                    +{selected.length - maxChips}
                  </span>
                )}
              </>
            : selected.length > 0 && <span className="truncate text-ink">{labelFor(selected[0])}</span>}
        </span>
        <span className="flex shrink-0 items-center gap-1">
          {selected.length > 0 && <span role="button" onClick={clear} className="cursor-pointer text-muted hover:text-rose-500"><X size={13} /></span>}
          <ChevronDown size={15} className={`text-muted transition-transform ${open ? 'rotate-180' : ''}`} />
        </span>
      </button>

      <Popover open={open} onClose={() => setOpen(false)} anchorRef={anchorRef} dir={dir} width={280} sheetTitle={placeholder}>
        {searchable && (
          <div className="tk-inset mb-2 flex items-center gap-2 px-3 py-2">
            <Search size={13} className="text-muted" />
            <input autoFocus value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search…"
              className="w-full bg-transparent font-body text-[13px] text-ink outline-none placeholder:text-muted" />
          </div>
        )}
        <div className="hide-scrollbar max-h-56 overflow-y-auto">
          {filtered.length === 0 && <p className="px-3 py-4 text-center font-body text-[12.5px] text-muted">No matches</p>}
          {filtered.map((o) => {
            const on = selected.includes(o.value);
            return (
              <button key={o.value} onClick={() => toggle(o.value)}
                className={`flex w-full items-center justify-between gap-2 rounded-lg px-3 py-2 text-left font-body text-[13px] transition hover:bg-primary/8 ${on ? 'font-bold text-primary' : 'text-ink/80'}`}>
                <span className="min-w-0">
                  <span className="block truncate">{o.label}</span>
                  {o.hint && <span className="block truncate text-[11px] text-muted">{o.hint}</span>}
                </span>
                {on && <Check size={14} className="shrink-0" />}
              </button>
            );
          })}
        </div>
        {props.multi && (
          <div className="mt-2 flex justify-between border-t tk-divider pt-2">
            <button onClick={() => props.onChange(filtered.map((o) => o.value))} className="font-body text-[12px] font-bold text-primary hover:underline">Select all</button>
            <button onClick={() => props.onChange([])} className="font-body text-[12px] font-bold text-muted hover:text-ink">Clear</button>
          </div>
        )}
      </Popover>
    </div>
  );
}
