// rust-svelte-stack/frontend/src/lib/components/Login.svelte
<script lang="ts">
  // Mirror of React src/pages/Login.tsx — luxury auth card with the full
  // flap-sweep transition: the forest overlay expands via clip-path to cover
  // the card, form/mode/side swap at midpoint, flap retracts to the opposite
  // angled rest, incoming content staggers upward (sweep 680ms,
  // cubic-bezier(.83,0,.17,1); stagger delays 50–540ms).
  let mode: 'in' | 'up' = $state('in');
  let side: 'right' | 'left' = $state('right');
  let covering = $state(false);
  let phase: 'in' | 'out' | 'pre' = $state('in');
  let animating = false;

  function toggleFlap() {
    if (animating) return;
    animating = true;
    phase = 'out';
    covering = true;
    setTimeout(() => {
      mode = mode === 'in' ? 'up' : 'in';
      side = side === 'right' ? 'left' : 'right';
      phase = 'pre';
      covering = false;
      requestAnimationFrame(() => requestAnimationFrame(() => (phase = 'in')));
    }, 680);
    setTimeout(() => (animating = false), 1360);
  }
  let email = $state('');
  let password = $state('');
  let fullName = $state('');
  let error = $state('');
  let busy = $state(false);

  async function submit(e: SubmitEvent) {
    e.preventDefault();
    error = '';
    if (password.length < 6) { error = 'Password must be at least 6 characters.'; return; }
    busy = true;
    try {
      const res = await fetch(`/api/v1/auth/${mode === 'in' ? 'login' : 'signup'}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password, full_name: fullName || undefined }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Authentication failed');
      localStorage.setItem('aviary-jwt', json.token);
      location.href = '/home';
    } catch (err) {
      error = err instanceof Error ? err.message : 'Authentication failed';
    } finally { busy = false; }
  }
</script>

<div class="page">
  <div class="card">
    <aside class="brand">
      <p class="masthead">Aviary <i class="dot"></i> People OS</p>
      <div>
        <p class="eyebrow">Est. 2019 · Bengaluru</p>
        <h2>The quiet luxury of<br /><em>effortless HR.</em></h2>
        <p class="sub">Attendance, payroll, people and structure — one serene workspace for 1,000+ organizations.</p>
      </div>
      <p class="foot">— Members only —</p>
    </aside>

    <section class="form">
      <p class="eyebrow gold">{mode === 'in' ? 'Member access' : 'New membership'}</p>
      <h1>{mode === 'in' ? 'Welcome' : 'Join the'} <em>{mode === 'in' ? 'back.' : 'house.'}</em></h1>

      <form onsubmit={submit}>
        {#if mode === 'up'}
          <label><span>Full name</span><input type="text" bind:value={fullName} placeholder="Asha Verma" required /></label>
        {/if}
        <label><span>Email address</span><input type="email" bind:value={email} placeholder="you@company.com" required /></label>
        <label><span>Password</span><input type="password" bind:value={password} placeholder="••••••••••" required /></label>
        {#if error}<p class="err">{error}</p>{/if}
        <button class="cta" disabled={busy}>{busy ? 'One moment…' : mode === 'in' ? 'Enter workspace' : 'Create account'} →</button>
      </form>

      <p class="switch">
        {mode === 'in' ? 'New to Aviary?' : 'Already a member?'}
        <button onclick={() => { error = ''; toggleFlap(); }}>
          {mode === 'in' ? 'Create an account' : 'Sign in'}
        </button>
      </p>
    </section>
  </div>
</div>

<style>
  :global(:root) { --lux-cream: #f5efe3; --lux-card: #fbf7ef; --lux-gold: #c6a15b;
    --lux-gold-soft: #e2cd9c; --lux-ink: #1f2a20; --lux-muted: #6f7a68;
    --lux-line: rgba(31,42,32,0.16); --lux-f7: #223a2a; --lux-f8: #16261c; --lux-f9: #101d15; }
  .page { min-height: 100vh; display: grid; place-items: center; padding: 24px;
    background: radial-gradient(ellipse at 20% 10%, rgba(198,161,91,0.16), transparent 55%), var(--lux-cream); }
  .card { display: grid; grid-template-columns: 1.05fr 1fr; width: min(880px, 100%);
    border-radius: 26px; overflow: hidden; background: var(--lux-card);
    box-shadow: 0 32px 80px rgba(31,42,32,0.22); animation: rise 0.7s cubic-bezier(0.22,1,0.36,1) both; }
  @keyframes rise { from { opacity: 0; transform: translateY(24px) scale(0.985); } }
  .brand { display: flex; flex-direction: column; justify-content: space-between; padding: 40px;
    background: linear-gradient(160deg, var(--lux-f7), var(--lux-f8) 55%, var(--lux-f9));
    box-shadow: inset 0 0 0 1px rgba(226,205,156,0.07); }
  .masthead { font: 700 11px 'Outfit', sans-serif; letter-spacing: 0.3em; text-transform: uppercase; color: var(--lux-gold-soft); }
  .dot { display: inline-block; width: 4px; height: 4px; border-radius: 999px; background: var(--lux-gold); margin: 0 6px 2px; }
  .brand h2 { font: 500 36px/1.14 'Fraunces', serif; color: #fff; }
  .brand h2 em { color: var(--lux-gold-soft); }
  .brand .sub { margin-top: 14px; max-width: 340px; font: 400 13.5px/1.6 'Outfit', sans-serif; color: rgba(255,255,255,0.55); }
  .eyebrow { font: 700 10.5px 'Outfit', sans-serif; letter-spacing: 0.28em; text-transform: uppercase; color: var(--lux-gold); margin-bottom: 10px; }
  .foot { font: 500 10px 'Outfit', sans-serif; letter-spacing: 0.3em; text-transform: uppercase; color: rgba(255,255,255,0.35); text-align: center; }
  .form { padding: 40px; }
  .form h1 { font: 500 30px 'Fraunces', serif; color: var(--lux-ink); }
  .form h1 em { color: var(--lux-gold); }
  form { margin-top: 26px; display: flex; flex-direction: column; gap: 20px; }
  label span { display: block; font: 700 10.5px 'Outfit', sans-serif; letter-spacing: 0.22em;
    text-transform: uppercase; color: var(--lux-muted); margin-bottom: 6px; }
  input { width: 100%; background: transparent; border: 0; border-bottom: 1px solid var(--lux-line);
    padding: 6px 0 8px; font: 500 14.5px 'Outfit', sans-serif; color: var(--lux-ink); outline: none; }
  input:focus { border-bottom: 2px solid var(--lux-gold); }
  .cta { border-radius: 999px; padding: 14px; font: 700 13px 'Outfit', sans-serif;
    letter-spacing: 0.18em; text-transform: uppercase; color: #fff;
    background: linear-gradient(135deg, var(--lux-gold), #a9853f);
    box-shadow: 0 10px 26px rgba(198,161,91,0.4); }
  .cta:active { transform: scale(0.98); }
  .err { font: 600 12.5px 'Outfit', sans-serif; color: #b32222; background: rgba(214,48,48,0.08);
    border-radius: 12px; padding: 9px 14px; }
  .switch { margin-top: 20px; text-align: center; font: 500 12.5px 'Outfit', sans-serif; color: var(--lux-muted); }
  .switch button { color: var(--lux-gold); font-weight: 700; text-decoration: underline; text-underline-offset: 4px; }
  /* ---- flap sweep (mirrors React .lx-* classes) ---- */
  :global(.lx-flap) { position: absolute; inset: 0; z-index: 10;
    background: radial-gradient(900px 500px at 20% 0%, rgba(198,161,91,0.14), transparent 55%),
      linear-gradient(155deg, #223a2a 0%, #16261c 55%, #101d15 100%);
    transition: clip-path 0.68s cubic-bezier(0.83, 0, 0.17, 1); will-change: clip-path; }
  :global(.lx-flap.rest-right) { clip-path: polygon(46% 0%, 100% 0%, 100% 100%, 60% 100%); }
  :global(.lx-flap.rest-left) { clip-path: polygon(0% 0%, 54% 0%, 40% 100%, 0% 100%); }
  :global(.lx-flap.covering) { clip-path: polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%) !important; }
  :global(.lx-stagger) { opacity: 0; transform: translateY(22px); transition: none; }
  :global(.lx-in .lx-stagger) { opacity: 1; transform: translateY(0);
    transition: opacity 0.5s cubic-bezier(0.22,1,0.36,1), transform 0.5s cubic-bezier(0.22,1,0.36,1); }
  :global(.lx-in .lx-stagger:nth-child(1)) { transition-delay: 0.05s; }
  :global(.lx-in .lx-stagger:nth-child(2)) { transition-delay: 0.12s; }
  :global(.lx-in .lx-stagger:nth-child(3)) { transition-delay: 0.19s; }
  :global(.lx-in .lx-stagger:nth-child(4)) { transition-delay: 0.26s; }
  :global(.lx-out .lx-stagger) { opacity: 0; transform: translateY(-14px);
    transition: opacity 0.26s ease, transform 0.26s ease; }
  @media (max-width: 860px) { .card { grid-template-columns: 1fr; } .brand { display: none; } }
</style>

// src/pages/Login.tsx
import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Mail, Lock, ArrowRight, AlertCircle, User, Feather } from 'lucide-react';
import supabase from '../lib/supabase';
import { signInWithGoogle } from '../lib/googleAuth';
import { useAuth } from '../contexts/AuthContext';

/*
 * Full-screen neumorphic auth. Token-driven (Soft UI by default; every
 * theme restyles it automatically). Keeps the signature flap-sweep:
 *  Phase 0  outgoing content lifts away as the sweep begins
 *  Phase 1  the flap expands (clip-path) to cover the screen
 *  Midpoint form column + flap resting side swap while hidden
 *  Phase 2  flap retracts to the opposite angled rest
 *  Phase 3  incoming content staggers upward into view
 */

const EXPAND_MS = 680;

function Field({ label, type, value, onChange, placeholder, icon }: {
  label: string; type: string; value: string; onChange: (v: string) => void;
  placeholder: string; icon: React.ReactNode;
}) {
  return (
    <label className="lx-stagger block">
      <span className="mb-1.5 block font-body text-[10.5px] font-bold uppercase tracking-[0.18em] text-muted">{label}</span>
      <span className="tk-input flex items-center gap-2.5 px-4 py-3">
        <span className="shrink-0 text-primary">{icon}</span>
        <input type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder}
          className="w-full bg-transparent font-body text-[14px] text-ink outline-none placeholder:text-muted" />
      </span>
    </label>
  );
}

export default function Login() {
  const navigate = useNavigate();
  const { user, loading } = useAuth();
  const [mode, setMode] = useState<'in' | 'up'>('in');
  const [side, setSide] = useState<'right' | 'left'>('right');
  const [covering, setCovering] = useState(false);
  const [phase, setPhase] = useState<'in' | 'out' | 'pre'>('pre');
  const animating = useRef(false);

  const [name, setName] = useState('');
  const [email, setEmail] = useState('demo@example.com');
  const [password, setPassword] = useState('password123');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  useEffect(() => { if (!loading && user) navigate('/home', { replace: true }); }, [user, loading, navigate]);
  useEffect(() => {
    const t = setTimeout(() => setPhase('in'), 60);
    return () => clearTimeout(t);
  }, []);

  const toggleForm = () => {
    if (animating.current) return;
    animating.current = true;
    setError('');
    setPhase('out');
    setCovering(true);
    setTimeout(() => {
      setMode((m) => (m === 'in' ? 'up' : 'in'));
      setSide((s) => (s === 'right' ? 'left' : 'right'));
      setPhase('pre');
      setCovering(false);
      requestAnimationFrame(() => requestAnimationFrame(() => setPhase('in')));
    }, EXPAND_MS);
    setTimeout(() => { animating.current = false; }, EXPAND_MS * 2);
  };

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    if (!email.trim() || !password.trim()) { setError('Email and password are required.'); return; }
    if (password.length < 6) { setError('Password must be at least 6 characters.'); return; }
    setBusy(true);
    try {
      if (mode === 'up') {
        const { error } = await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } });
        if (error) throw error;
      } else {
        const { error } = await supabase.auth.signInWithPassword({ email, password });
        if (error) throw error;
      }
      navigate('/home');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Authentication failed');
    } finally { setBusy(false); }
  };

  const staggerCls = phase === 'in' ? 'lx-in' : phase === 'out' ? 'lx-out' : '';

  const googleBtn = (
    <button onClick={() => signInWithGoogle('Aviary HRMS')}
      className="lx-stagger tk-btn-ghost flex w-full items-center justify-center gap-3 rounded-full py-3 font-body text-[13px] font-semibold">
      <svg width="17" height="17" viewBox="0 0 24 24"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 0 1-2.2 3.32v2.77h3.57c2.08-1.92 3.27-4.74 3.27-8.1z"/><path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84A11 11 0 0 0 12 23z"/><path fill="#FBBC05" d="M5.84 14.1a6.6 6.6 0 0 1 0-4.2V7.06H2.18a11 11 0 0 0 0 9.88l3.66-2.84z"/><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15A11 11 0 0 0 2.18 7.06l3.66 2.84c.87-2.6 3.3-4.52 6.16-4.52z"/></svg>
      Continue with Google
    </button>
  );

  const formCore = (
    <>
      <p className="lx-stagger mb-2 font-body text-[10.5px] font-bold uppercase tracking-[0.28em] text-primary">
        {mode === 'in' ? 'Member access' : 'New membership'}
      </p>
      <h1 className="lx-stagger font-display text-[32px] font-semibold leading-tight text-ink">
        {mode === 'in' ? <>Welcome <em className="text-primary">back.</em></> : <>Join the <em className="text-primary">house.</em></>}
      </h1>
      <p className="lx-stagger mt-1.5 font-body text-[13px] text-muted">
        {mode === 'in' ? 'Sign in to continue exactly where you left off.' : 'Create your account for your organization\u2019s workspace.'}
      </p>

      <form onSubmit={submit} className="mt-7 space-y-4">
        {mode === 'up' && <Field label="Full name" type="text" value={name} onChange={setName} placeholder="Asha Verma" icon={<User size={15} />} />}
        <Field label="Email address" type="email" value={email} onChange={setEmail} placeholder="you@company.com" icon={<Mail size={15} />} />
        <Field label="Password" type="password" value={password} onChange={setPassword} placeholder="••••••••••" icon={<Lock size={15} />} />
        {error && (
          <p className="flex items-center gap-2 rounded-xl bg-rose-500/10 px-3.5 py-2.5 font-body text-[12.5px] text-rose-500">
            <AlertCircle size={14} /> {error}
          </p>
        )}
        <button type="submit" disabled={busy}
          className="lx-stagger tk-btn-primary group flex w-full items-center justify-center gap-2.5 rounded-full py-3.5 font-body text-[13px] font-bold uppercase tracking-[0.16em]">
          {busy ? 'One moment…' : mode === 'in' ? 'Enter workspace' : 'Create account'}
          <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" />
        </button>
      </form>

      <div className="lx-stagger my-5 flex items-center gap-3">
        <span className="h-px flex-1 border-t tk-divider" />
        <span className="font-body text-[10px] font-bold uppercase tracking-[0.25em] text-muted">or</span>
        <span className="h-px flex-1 border-t tk-divider" />
      </div>
      {googleBtn}
      {mode === 'in' && (
        <p className="lx-stagger tk-chip mt-5 px-4 py-2 text-center font-body text-[11.5px] text-muted">
          <b className="text-gold-deep">Demo</b> — demo@example.com · password123
        </p>
      )}
    </>
  );

  return (
    <div className="relative h-screen w-screen overflow-hidden bg-paper">
      {/* soft ambient shapes */}
      <div className="tk-raise-sm pointer-events-none absolute -left-24 -top-24 h-72 w-72 rounded-full opacity-60" />
      <div className="tk-inset pointer-events-none absolute -bottom-32 -right-20 h-96 w-96 rounded-full opacity-50" />

      {/* ===== Form column (desktop) — swaps sides with the flap ===== */}
      <div className={`absolute inset-y-0 hidden w-[50%] lg:block ${side === 'right' ? 'left-0' : 'right-0'}`}>
        <div className={`flex h-full flex-col justify-center overflow-y-auto px-12 py-8 xl:px-24 ${staggerCls}`}>
          <div className="mx-auto w-full max-w-md">{formCore}</div>
        </div>
      </div>

      {/* ===== Flap (accent panel, clip-path sweep) ===== */}
      <div className={`lx-flap hidden lg:block ${side === 'right' ? 'rest-right' : 'rest-left'} ${covering ? 'covering' : ''}`}>
        <div className={`absolute inset-y-0 flex w-[38%] flex-col justify-center ${side === 'right' ? 'right-0 pl-4 pr-14' : 'left-0 pl-14 pr-4'} ${staggerCls}`}>
          <div className="lx-stagger mb-4 flex items-center gap-2.5">
            <span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-white/10 shadow-lg">
              <Feather size={18} className="text-lime-glow" />
            </span>
            <span>
              <span className="block font-display text-[17px] font-bold leading-none text-white">Aviary</span>
              <span className="block font-body text-[9px] font-bold uppercase tracking-[0.24em] text-white/50">People OS</span>
            </span>
          </div>
          <h2 className="lx-stagger font-display text-[30px] font-medium leading-[1.15] text-white">
            {mode === 'in'
              ? <>The quiet luxury of <em className="text-lime-glow">effortless HR.</em></>
              : <>Begin your <em className="text-lime-glow">membership.</em></>}
          </h2>
          <p className="lx-stagger mt-3.5 font-body text-[13px] leading-relaxed text-white/60">
            {mode === 'in'
              ? 'Attendance, payroll, people and structure — curated into one serene workspace.'
              : 'Early access, private onboarding and a workspace tailored to your organization.'}
          </p>
          <button onClick={toggleForm}
            className="lx-stagger mt-7 w-fit rounded-full border border-white/30 px-6 py-2.5 font-body text-[11.5px] font-bold uppercase tracking-[0.18em] text-white transition hover:bg-white/10 active:scale-[0.97]">
            {mode === 'in' ? 'Create an account' : 'Sign in instead'}
          </button>
        </div>
      </div>

      {/* ===== Mobile: single full-screen column ===== */}
      <div className={`flex h-full items-center overflow-y-auto px-6 py-8 lg:hidden ${staggerCls}`}>
        <div className="mx-auto w-full max-w-md">
          <div className="lx-stagger mb-6 flex items-center gap-2.5">
            <span className="tk-raise-sm flex h-10 w-10 items-center justify-center rounded-2xl">
              <Feather size={17} className="text-primary" />
            </span>
            <span>
              <span className="block font-display text-[16px] font-bold leading-none text-ink">Aviary</span>
              <span className="block font-body text-[9px] font-bold uppercase tracking-[0.22em] text-muted">People OS</span>
            </span>
          </div>
          {formCore}
          <p className="lx-stagger mt-5 text-center font-body text-[12.5px] text-muted">
            {mode === 'in' ? 'New to Aviary?' : 'Already a member?'}{' '}
            <button onClick={() => { setMode(mode === 'in' ? 'up' : 'in'); setError(''); }}
              className="font-bold text-primary underline underline-offset-4">
              {mode === 'in' ? 'Create an account' : 'Sign in'}
            </button>
          </p>
        </div>
      </div>
    </div>
  );
}
