// src/shared/pickers/DateRangePicker.tsx
import { useState } from 'react';
import { CalendarRange } from 'lucide-react';
import PickerField from './PickerField';
import { CalendarGrid, MonthNav, dstr } from './DatePicker';
import { useIsMobile } from '../primitives';

export interface DateRange { start: string; end: string }

const prettyY = (v: string) => v ? new Date(v + 'T00:00:00').toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: '2-digit' }) : '';

const PRESETS: { label: string; days: number }[] = [
  { label: '7 Days', days: 7 },
  { label: '15 Days', days: 15 },
  { label: '30 Days', days: 30 },
  { label: '45 Days', days: 45 },
  { label: '90 Days', days: 90 },
];

export default function DateRangePicker({ value, onChange, placeholder = 'Pick a range', className = '' }: {
  value: DateRange; onChange: (v: DateRange) => void; placeholder?: string; className?: string;
}) {
  const [open, setOpen] = useState(false);
  const mobile = useIsMobile();
  const [month, setMonth] = useState(() => value.start ? new Date(value.start + 'T00:00:00') : new Date());
  const [draft, setDraft] = useState<DateRange>(value);
  const [hover, setHover] = useState<string | null>(null);
  const [activePreset, setActivePreset] = useState<number | null>(null);

  // display always includes the year
  const display = value.start && value.end ? `${prettyY(value.start)} → ${prettyY(value.end)}` : '';

  const openPicker = (o: boolean) => {
    if (o) { setDraft(value); setHover(null); setActivePreset(null); if (value.start) setMonth(new Date(value.start + 'T00:00:00')); }
    setOpen(o);
  };

  const pick = (v: string) => {
    setActivePreset(null);
    if (!draft.start || (draft.start && draft.end)) { setDraft({ start: v, end: '' }); setHover(null); }
    else if (v < draft.start) { setDraft({ start: v, end: draft.start }); setHover(null); }
    else { setDraft({ start: draft.start, end: v }); setHover(null); }
  };

  const applyPreset = (i: number) => {
    const end = dstr(new Date());
    const start = dstr(new Date(Date.now() - (PRESETS[i].days - 1) * 864e5));
    setDraft({ start, end });
    setActivePreset(i);
    setMonth(new Date(start + 'T00:00:00'));
  };

  const eff: DateRange = (() => {
    if (draft.start && draft.end) return draft;
    if (draft.start && hover) return hover < draft.start ? { start: hover, end: draft.start } : { start: draft.start, end: hover };
    return draft;
  })();

  const isStart = (v: string) => !!eff.start && v === eff.start;
  const isEnd = (v: string) => !!eff.end && v === eff.end;
  const isInRange = (v: string) => !!(eff.start && eff.end && v > eff.start && v < eff.end);
  const month2 = new Date(month.getFullYear(), month.getMonth() + 1, 1);

  return (
    <PickerField display={display} placeholder={placeholder} icon={<CalendarRange size={15} />}
      open={open} setOpen={openPicker}
      width={mobile ? 330 : 600} label={placeholder} className={className}>

      <div className={mobile ? '' : 'flex gap-4'}>
        {/* presets — left rail on desktop, horizontal scroll on mobile */}
        <div className={mobile
          ? 'hide-scrollbar mb-3 flex gap-2 overflow-x-auto pb-1'
          : 'flex w-[92px] shrink-0 flex-col gap-2 border-r tk-divider pr-3'}>
          {PRESETS.map((p, i) => (
            <button key={p.label} onClick={() => applyPreset(i)}
              className={`cal-preset !flex-none !px-2.5 !py-2 text-[11.5px] ${activePreset === i ? 'active' : ''}`}>
              {p.label}
            </button>
          ))}
        </div>

        {/* calendars — fixed 6-week height */}
        <div className={mobile ? '' : 'flex flex-1 gap-4'}>
          <div className="min-w-0 flex-1">
            <MonthNav month={month} onMonth={setMonth} side={mobile ? 'both' : 'left'} />
            <CalendarGrid month={month} isStart={isStart} isEnd={isEnd} isInRange={isInRange} onPick={pick} onHover={setHover} />
          </div>
          {!mobile && (
            <div className="min-w-0 flex-1">
              <MonthNav month={month2} onMonth={(d) => setMonth(new Date(d.getFullYear(), d.getMonth() - 1, 1))} side="right" />
              <CalendarGrid month={month2} isStart={isStart} isEnd={isEnd} isInRange={isInRange} onPick={pick} onHover={setHover} />
            </div>
          )}
        </div>
      </div>

      <div className="mt-3 flex items-center justify-between gap-3 border-t tk-divider pt-2.5">
        <p className="truncate font-body text-[11px] text-muted">
          {!draft.start ? 'Select start date' : !draft.end ? 'Hover to preview · pick end' : `${prettyY(draft.start)} → ${prettyY(draft.end)}`}
        </p>
        <div className="flex shrink-0 gap-2">
          <button onClick={() => { setDraft({ start: '', end: '' }); setHover(null); setActivePreset(null); }} className="cal-clear !px-3.5 !py-1.5 text-[12px]">Clear</button>
          <button onClick={() => { onChange(draft.end ? draft : { start: '', end: '' }); setOpen(false); }}
            disabled={!!draft.start && !draft.end}
            className="cal-submit !px-5 !py-1.5 text-[12px] disabled:opacity-50">Submit</button>
        </div>
      </div>
    </PickerField>
  );
}

// rust-svelte-stack/frontend/src/lib/components/pickers/DateRangePicker.svelte
<script lang="ts">
  // Mirror of React src/shared/pickers/DateRangePicker.tsx — recessed display
  // slot, preset tabs, dual fixed-height (42-cell) calendars, trench range
  // with hover preview, raised start/end badges, Clear + Submit commit flow.
  export interface DateRange { start: string; end: string }
  let { value = $bindable({ start: '', end: '' } as DateRange) } = $props();

  let open = $state(false);
  let month = $state(value.start ? new Date(value.start) : new Date());
  let draft = $state({ ...value });
  let hover: string | null = $state(null);

  const dstr = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  const PRESETS = [7, 15, 30, 45];

  const eff = $derived.by((): DateRange => {
    if (draft.start && draft.end) return draft;
    if (draft.start && hover) return hover < draft.start ? { start: hover, end: draft.start } : { start: draft.start, end: hover };
    return draft;
  });

  function pick(v: string) {
    if (!draft.start || (draft.start && draft.end)) draft = { start: v, end: '' };
    else if (v < draft.start) draft = { start: v, end: draft.start };
    else draft = { start: draft.start, end: v };
    hover = null;
  }
  function preset(days: number) {
    draft = { start: dstr(new Date(Date.now() - (days - 1) * 864e5)), end: dstr(new Date()) };
    month = new Date(draft.start);
  }
  function cells(base: Date) {
    const y = base.getFullYear(), m = base.getMonth();
    const firstDow = new Date(y, m, 1).getDay();
    const days = new Date(y, m + 1, 0).getDate();
    return Array.from({ length: 42 }, (_, i) => {
      const d = i - firstDow + 1;
      return d >= 1 && d <= days ? { d, v: dstr(new Date(y, m, d)) } : null;
    });
  }
  const month2 = $derived(new Date(month.getFullYear(), month.getMonth() + 1, 1));
</script>

{#snippet pane(base: Date, side: 'left' | 'right')}
  <div class="pane">
    <div class="nav">
      {#if side === 'left'}<button class="cal-nav" onclick={() => (month = new Date(month.getFullYear(), month.getMonth() - 1))}>‹</button>{:else}<span class="sp"></span>{/if}
      <b class="title">{base.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</b>
      {#if side === 'right'}<button class="cal-nav" onclick={() => (month = new Date(month.getFullYear(), month.getMonth() + 1))}>›</button>{:else}<span class="sp"></span>{/if}
    </div>
    <div class="grid" onmouseleave={() => (hover = null)}>
      {#each ['Su','Mo','Tu','We','Th','Fr','Sa'] as d}<span class="dow">{d}</span>{/each}
      {#each cells(base) as c, i (i)}
        {#if !c}<span class="day muted"></span>
        {:else}
          {@const isStart = eff.start === c.v}
          {@const isEnd = eff.end === c.v}
          {@const inR = !!(eff.start && eff.end && c.v > eff.start && c.v < eff.end)}
          <button class="day" class:trench={inR || isStart || isEnd} class:capl={isStart} class:capr={isEnd}
            onmouseenter={() => (hover = c.v)} onclick={() => pick(c.v)}>
            {#if isStart || isEnd}<span class="badge">{c.d}</span>{:else}{c.d}{/if}
          </button>
        {/if}
      {/each}
    </div>
  </div>
{/snippet}

<div class="root">
  <button class="tk-input field" onclick={() => { draft = { ...value }; open = !open; }}>
    {value.start && value.end ? `${value.start} → ${value.end}` : 'Pick a range'} <span>⧉</span>
  </button>
  {#if open}
    <div class="tk-pop panel">
      <div class="tk-inset display">
        <span class:ph={!eff.start}>{eff.start || 'Start Date'}</span>
        <span class="arrow">→</span>
        <span class:ph={!eff.end}>{eff.end || 'End Date'}</span>
      </div>
      <div class="presets">
        {#each PRESETS as p}<button class="cal-preset" onclick={() => preset(p)}>Last {p} Days</button>{/each}
      </div>
      <div class="cals">
        {@render pane(month, 'left')}
        {@render pane(month2, 'right')}
      </div>
      <div class="actions">
        <button class="cal-clear" onclick={() => { draft = { start: '', end: '' }; hover = null; }}>Clear</button>
        <button class="cal-submit" disabled={!!draft.start && !draft.end}
          onclick={() => { value = draft.end ? draft : { start: '', end: '' }; open = false; }}>Submit</button>
      </div>
    </div>
  {/if}
</div>

<style>
  .root { position: relative; }
  .field { display: flex; justify-content: space-between; width: 100%; padding: 9px 14px;
    font: 500 14px var(--t-font-body); color: var(--t-ink); }
  .panel { position: fixed; left: 50%; top: 50%; transform: translate(-50%, -50%);
    width: min(700px, calc(100vw - 24px)); padding: 18px; z-index: 60; }
  .display { display: flex; justify-content: space-between; align-items: center;
    padding: 12px 18px; border-radius: 16px; margin-bottom: 12px;
    font: 600 13px var(--t-font-body); color: var(--t-ink); }
  .display .ph { opacity: 0.5; font-weight: 400; }
  .arrow { color: var(--t-accent); font-weight: 700; }
  .presets { display: flex; gap: 10px; margin-bottom: 14px; }
  .cal-preset { flex: 1; padding: 9px; border-radius: 13px; background: var(--t-surface);
    box-shadow: var(--t-shadow-card); font: 600 12px var(--t-font-body); color: var(--t-ink); }
  .cal-preset:active { box-shadow: var(--t-inset); color: var(--t-accent); }
  .cals { display: flex; gap: 26px; }
  .pane { flex: 1; }
  .nav { display: flex; justify-content: space-between; align-items: center; height: 36px; margin-bottom: 10px; }
  .title { min-width: 148px; text-align: center; font: 600 14px var(--t-font-body); color: var(--t-ink); }
  .sp { width: 34px; }
  .cal-nav { width: 34px; height: 34px; border-radius: 50%; background: var(--t-surface);
    box-shadow: var(--t-shadow-card); color: var(--t-accent); font-size: 16px; }
  .cal-nav:active { box-shadow: var(--t-inset); }
  .grid { display: grid; grid-template-columns: repeat(7, 1fr); row-gap: 6px; }
  .dow { text-align: center; font: 700 10px var(--t-font-body); text-transform: uppercase; color: var(--t-muted); padding-bottom: 4px; }
  .day { height: 38px; display: flex; align-items: center; justify-content: center;
    font: 500 12.5px var(--t-font-body); color: var(--t-ink); position: relative; }
  .day.muted { pointer-events: none; }
  .day:hover:not(.trench) { background: var(--t-surface); box-shadow: var(--t-shadow-card); border-radius: 50%; z-index: 2; }
  .day.trench { background: var(--t-surface);
    box-shadow: inset 0 4px 5px var(--neu-dark, rgba(0,0,0,0.14)), inset 0 -4px 5px var(--neu-light, rgba(255,255,255,0.75)); }
  .day.capl { border-radius: 20px 0 0 20px; }
  .day.capr { border-radius: 0 20px 20px 0; }
  .day.capl.capr { border-radius: 20px; }
  .badge { width: 32px; height: 32px; border-radius: 50%; display: flex; align-items: center; justify-content: center;
    background: var(--t-accent); color: #fff; font-weight: 600;
    box-shadow: 3px 3px 7px color-mix(in srgb, var(--t-accent-deep) 55%, transparent), -2px -2px 5px rgba(255,255,255,0.65); }
  .actions { display: flex; justify-content: flex-end; gap: 12px; margin-top: 16px; }
  .cal-clear { padding: 10px 22px; border-radius: 13px; background: var(--t-surface);
    box-shadow: var(--t-shadow-card); font: 600 13px var(--t-font-body); color: var(--t-ink); }
  .cal-submit { padding: 10px 26px; border-radius: 13px; background: var(--t-accent); color: #fff;
    font: 700 13px var(--t-font-body);
    box-shadow: 3px 3px 7px color-mix(in srgb, var(--t-accent-deep) 50%, transparent); }
  .cal-submit:disabled { opacity: 0.5; }
  @media (max-width: 720px) { .cals { flex-direction: column; } .pane:last-child { display: none; } }
</style>
