// src/shared/pickers/MonthPicker.tsx
import { useState } from 'react';
import { Calendar, ChevronLeft, ChevronRight } from 'lucide-react';
import PickerField from './PickerField';
import { MONTHS_SHORT, MONTHS } from '../../lib/api';

const pretty = (v: string) => {
  if (!v) return '';
  const [y, m] = v.split('-').map(Number);
  return `${MONTHS[m - 1]} ${y}`;
};
const prettyShort = (v: string) => {
  if (!v) return '';
  const [y, m] = v.split('-').map(Number);
  return `${MONTHS_SHORT[m - 1]} ${y}`;
};
const mval = (y: number, m: number) => `${y}-${String(m + 1).padStart(2, '0')}`;

function YearGrid({ year, setYear, isStart, isEnd, isInRange, onPick, onHover }: {
  year: number; setYear: (y: number) => void;
  isStart: (v: string) => boolean; isEnd: (v: string) => boolean; isInRange: (v: string) => boolean;
  onPick: (v: string) => void; onHover?: (v: string | null) => void;
}) {
  const yearBase = new Date().getFullYear();
  return (
    <div>
      <div className="mb-2.5 flex h-9 items-center justify-between">
        <button onClick={() => setYear(year - 1)} className="cal-nav"><ChevronLeft size={15} /></button>
        <select value={year} onChange={(e) => setYear(+e.target.value)}
          className="tk-input rounded-lg px-2.5 py-1.5 font-body text-[12.5px] font-bold">
          {Array.from({ length: 14 }, (_, i) => yearBase - 10 + i).map((yy) => <option key={yy}>{yy}</option>)}
        </select>
        <button onClick={() => setYear(year + 1)} className="cal-nav"><ChevronRight size={15} /></button>
      </div>
      <div className="grid grid-cols-3 gap-y-1.5" onMouseLeave={() => onHover?.(null)}>
        {MONTHS_SHORT.map((mo, i) => {
          const v = mval(year, i);
          const start = isStart(v), end = isEnd(v), inR = isInRange(v);
          const trench = inR || start || end;
          const col = i % 3;
          const capL = start || (trench && col === 0);
          const capR = end || (trench && col === 2);
          return (
            <button key={mo} onClick={() => onPick(v)} onMouseEnter={() => onHover?.(v)}
              className={[
                'cal-day sq interactive !h-11',
                trench ? 'in-trench' : '',
                capL ? 'trench-l' : '',
                capR ? 'trench-r' : '',
                (start || end) ? 'has-badge' : '',
              ].join(' ')}>
              {(start || end)
                ? <span className="cal-badge !h-[34px] !w-[52px] !rounded-[10px] text-[12px]">{mo}</span>
                : <span className="cal-inner"><span className="font-body text-[12.5px] font-semibold">{mo}</span></span>}
            </button>
          );
        })}
      </div>
    </div>
  );
}

export function MonthPicker({ value, onChange, placeholder = 'Pick a month', className = '' }: {
  value: string; onChange: (v: string) => void; placeholder?: string; className?: string;
}) {
  const [open, setOpen] = useState(false);
  const [year, setYear] = useState(() => value ? +value.split('-')[0] : new Date().getFullYear());
  return (
    <PickerField display={pretty(value)} placeholder={placeholder} icon={<Calendar size={15} />}
      open={open} setOpen={(o) => { setOpen(o); if (o && value) setYear(+value.split('-')[0]); }} width={252} className={className}>
      <YearGrid year={year} setYear={setYear}
        isStart={(v) => v === value} isEnd={(v) => v === value} isInRange={() => false}
        onPick={(v) => { onChange(v); setOpen(false); }} />
      <div className="mt-2.5 flex justify-end border-t tk-divider pt-2.5">
        <button onClick={() => { onChange(''); setOpen(false); }} className="cal-clear !px-3.5 !py-1.5 text-[12px]">Clear</button>
      </div>
    </PickerField>
  );
}

export interface MonthRange { start: string; end: string }

export function MonthRangePicker({ value, onChange, placeholder = 'Pick month range', className = '' }: {
  value: MonthRange; onChange: (v: MonthRange) => void; placeholder?: string; className?: string;
}) {
  const [open, setOpen] = useState(false);
  const [year, setYear] = useState(() => value.start ? +value.start.split('-')[0] : new Date().getFullYear());
  const [draft, setDraft] = useState<MonthRange>(value);
  const [hover, setHover] = useState<string | null>(null);

  const display = value.start && value.end ? `${prettyShort(value.start)} → ${prettyShort(value.end)}` : '';

  const pick = (v: string) => {
    if (!draft.start || (draft.start && draft.end)) setDraft({ start: v, end: '' });
    else if (v < draft.start) setDraft({ start: v, end: draft.start });
    else setDraft({ start: draft.start, end: v });
    setHover(null);
  };

  const eff: MonthRange = (() => {
    if (draft.start && draft.end) return draft;
    if (draft.start && hover) return hover < draft.start ? { start: hover, end: draft.start } : { start: draft.start, end: hover };
    return draft;
  })();

  return (
    <PickerField display={display} placeholder={placeholder} icon={<Calendar size={15} />}
      open={open} setOpen={(o) => { setOpen(o); if (o) { setDraft(value); setHover(null); if (value.start) setYear(+value.start.split('-')[0]); } }}
      width={252} className={className}>
      <YearGrid year={year} setYear={setYear}
        isStart={(v) => !!eff.start && v === eff.start}
        isEnd={(v) => !!eff.end && v === eff.end}
        isInRange={(v) => !!(eff.start && eff.end && v > eff.start && v < eff.end)}
        onPick={pick} onHover={setHover} />
      <div className="mt-2.5 flex items-center justify-between gap-2 border-t tk-divider pt-2.5">
        <p className="font-body text-[11px] text-muted">{!draft.start ? 'Pick start' : !draft.end ? 'Pick end' : `${prettyShort(draft.start)} → ${prettyShort(draft.end)}`}</p>
        <div className="flex gap-2">
          <button onClick={() => { setDraft({ start: '', end: '' }); setHover(null); }} className="cal-clear !px-3 !py-1.5 text-[12px]">Clear</button>
          <button onClick={() => { onChange(draft.end ? draft : { start: '', end: '' }); setOpen(false); }}
            disabled={!!draft.start && !draft.end}
            className="cal-submit !px-4 !py-1.5 text-[12px] disabled:opacity-50">Submit</button>
        </div>
      </div>
    </PickerField>
  );
}

// rust-svelte-stack/frontend/src/lib/components/pickers/MonthPicker.svelte
<script lang="ts">
  // Month + Month-Range picker — trench selection, square hover cells,
  // hover range preview, Submit/Clear commit flow. `range` prop switches modes.
  import { MONTHS, MONTHS_SHORT } from '$lib/api';

  let {
    value = $bindable(''),                              // single: 'YYYY-MM'
    rangeValue = $bindable({ start: '', end: '' }),     // range mode
    range = false,
    placeholder = 'Pick a month',
  } = $props();

  let open = $state(false);
  let year = $state(new Date().getFullYear());
  let draft = $state({ start: '', end: '' });
  let hover: string | null = $state(null);

  const mval = (y: number, m: number) => `${y}-${String(m + 1).padStart(2, '0')}`;
  const pretty = (v: string) => {
    if (!v) return '';
    const [y, m] = v.split('-').map(Number);
    return `${MONTHS_SHORT[m - 1]} ${y}`;
  };
  const display = $derived(range
    ? (rangeValue.start && rangeValue.end ? `${pretty(rangeValue.start)} → ${pretty(rangeValue.end)}` : '')
    : value ? `${MONTHS[+value.split('-')[1] - 1]} ${value.split('-')[0]}` : '');

  const eff = $derived.by(() => {
    if (!range) return { start: value, end: value };
    if (draft.start && draft.end) return draft;
    if (draft.start && hover) return hover < draft.start ? { start: hover, end: draft.start } : { start: draft.start, end: hover };
    return draft;
  });

  function toggle() {
    open = !open;
    if (open) {
      draft = { ...rangeValue };
      hover = null;
      const src = range ? rangeValue.start : value;
      if (src) year = +src.split('-')[0];
    }
  }
  function pick(v: string) {
    if (!range) { value = v; open = false; return; }
    if (!draft.start || (draft.start && draft.end)) draft = { start: v, end: '' };
    else if (v < draft.start) draft = { start: v, end: draft.start };
    else draft = { start: draft.start, end: v };
    hover = null;
  }
  function submit() {
    rangeValue = draft.end ? { ...draft } : { start: '', end: '' };
    open = false;
  }
</script>

<div class="root">
  <button class="tk-input field" onclick={toggle}>
    <span class:ph={!display}>{display || placeholder}</span><span class="ico">☷</span>
  </button>
  {#if open}
    <div class="tk-pop panel">
      <div class="nav">
        <button class="cal-nav" onclick={() => year--}>‹</button>
        <select class="tk-input ysel" bind:value={year}>
          {#each Array.from({ length: 14 }, (_, i) => new Date().getFullYear() - 10 + i) as y}<option value={y}>{y}</option>{/each}
        </select>
        <button class="cal-nav" onclick={() => year++}>›</button>
      </div>
      <div class="grid" role="grid" onmouseleave={() => (hover = null)}>
        {#each MONTHS_SHORT as mo, i (mo)}
          {@const v = mval(year, i)}
          {@const isStart = !!eff.start && v === eff.start}
          {@const isEnd = !!eff.end && v === eff.end}
          {@const inR = !!(eff.start && eff.end && v > eff.start && v < eff.end)}
          {@const col = i % 3}
          <button
            class="cal-day sq interactive"
            class:in-trench={inR || isStart || isEnd}
            class:trench-l={isStart || ((inR || isStart || isEnd) && col === 0)}
            class:trench-r={isEnd || ((inR || isStart || isEnd) && col === 2)}
            class:has-badge={isStart || isEnd}
            style="height:44px"
            onmouseenter={() => range && (hover = v)}
            onclick={() => pick(v)}>
            {#if isStart || isEnd}
              <span class="cal-badge sqb">{mo}</span>
            {:else}
              <span class="cal-inner"><span class="molbl">{mo}</span></span>
            {/if}
          </button>
        {/each}
      </div>
      <div class="foot">
        {#if range}
          <p class="hint">{!draft.start ? 'Pick start' : !draft.end ? 'Pick end' : `${pretty(draft.start)} → ${pretty(draft.end)}`}</p>
          <div class="btns">
            <button class="cal-clear sm" onclick={() => { draft = { start: '', end: '' }; hover = null; }}>Clear</button>
            <button class="cal-submit sm" disabled={!!draft.start && !draft.end} onclick={submit}>Submit</button>
          </div>
        {:else}
          <span></span>
          <button class="cal-clear sm" onclick={() => { value = ''; open = false; }}>Clear</button>
        {/if}
      </div>
    </div>
  {/if}
</div>

<style>
  .root { position: relative; }
  .field { display: flex; justify-content: space-between; align-items: center; width: 100%;
    padding: 9px 14px; font: 500 13.5px var(--t-font-body); color: var(--t-ink); }
  .ph { color: var(--t-muted); }
  .ico { color: var(--t-muted); }
  .panel { position: absolute; top: calc(100% + 6px); left: 0; width: 252px; padding: 12px; z-index: 60; }
  .nav { display: flex; justify-content: space-between; align-items: center; height: 36px; margin-bottom: 10px; }
  .ysel { padding: 6px 10px; font: 700 12.5px var(--t-font-body); border-radius: 10px; }
  .grid { display: grid; grid-template-columns: repeat(3, 1fr); row-gap: 6px; }
  .molbl { font: 600 12.5px var(--t-font-body); }
  .sqb { width: 52px !important; height: 34px !important; border-radius: 10px !important; font-size: 12px; }
  .foot { display: flex; justify-content: space-between; align-items: center; gap: 8px;
    margin-top: 10px; padding-top: 10px; border-top: 1px solid color-mix(in srgb, var(--t-ink) 8%, transparent); }
  .hint { margin: 0; font: 500 11px var(--t-font-body); color: var(--t-muted); }
  .btns { display: flex; gap: 8px; }
  .sm { padding: 6px 14px !important; font-size: 12px !important; }
</style>
